name: BookingTracker
version: "0.3.1"
slug: bookingtracker
description: Exact Booking.com reservation tracker
url: https://github.com/krsnak/bookingtracker
arch: [aarch64]
startup: application
boot: auto
ingress: true
ingress_port: 8000
homeassistant_api: true
panel_icon: mdi:calendar-search
options: {}
schema: {}
ports: {}
map: [data:rw]
init: false
